sdm example --- mv logistic regression
EcoJulia/SimpleSDMLayers.jl pull request #64
Opened 2021-02-27 19:06 UTC by gottacatchenall

2021-02-27 20:02 UTC, tpoisot commented
Here's my unsollicited review:

- add `Turing` to the `docs/Project.toml`
- avoid camelcase functions, they're advised against by [BlueStyle](https://github.com/invenia/BlueStyle) which most people implicitly follow
- add your name, etc, to the *main* `Project.toml`

I love the example, I'll have more feedback when the issues raised in #59 are solved (later tonight)

2021-02-27 20:29 UTC, gottacatchenall commented
sounds good, i'll make those changes and hopefully add some more text explaining whats happening tonight/tomorrow

2021-02-27 20:33 UTC, tpoisot commented
It would be cool to use the same occurrences across all examples, I think - I'm changing #61 to use the data from https://jcoliver.github.io/learn-r/011-species-distribution-models.html -- there's not too many points, and the spatial scale is relatively small

2021-02-28 02:32 UTC, tpoisot commented
I'm just going to make this catch up with master

2021-02-28 02:38 UTC, tpoisot commented
I'm also going to do a bunch of edits to make sure it follows the conventions of the package and other example

2021-02-28 03:26 UTC, tpoisot commented
Here's an output -- will push my code soon

![mvlogit](https://user-images.githubusercontent.com/579329/109406905-c1bf1b80-794a-11eb-95ba-8a52b074718c.png)

2021-02-28 03:30 UTC, tpoisot commented
And with this last commit, the example should run -- I'll let you add some text, etc. I might add another example using Flux where we sample the negatives within a radius around observations, that might be fun to write.

2021-02-28 04:46 UTC, tpoisot commented
Hmmmm.... we might have to scale this example down to get it to run in a reasonable amount of time. I'll think about something suitable.

2021-02-28 13:02 UTC, gottacatchenall commented
the saguaro data covers a much smaller spatial extent which could speed things up, and currently i'm using `MvNormal` and fitting all layers of worldclim (basically trying to overfit), which i think would be faster with fewer variables and a `Normal` for each

2021-02-28 15:33 UTC, tpoisot commented
What about the Corsican nuthatch? It's very limited in space (to Corsica), do we have enough observations on GBIF?

2021-02-28 19:08 UTC, gottacatchenall commented
Corsican nuthatch runs pretty fast even with all predictors. Added some text, might add more later

2021-02-28 20:45 UTC, tpoisot requested changes
Make sure the version of master is correct. there are a few files with changes that shouldn't have nay

2021-02-28 20:45 UTC, tpoisot commented on docs/src/sdm/mvlogistic.md
> +In this example, we build an SDM using Bayesian Multivariate Logistic Regression (using [Turing.jl]())
link missing

2021-02-28 20:45 UTC, tpoisot commented on docs/src/sdm/mvlogistic.md
> +We can get some occurrences for the taxon of interest, _Picea pungens_ or the
wrong taxon name

2021-02-28 20:45 UTC, tpoisot commented on docs/src/sdm/mvlogistic.md
> +    "limit" => 500
this is only going to get 300, which is the maximum allowed by GBIF API

2021-02-28 20:45 UTC, tpoisot commented on docs/src/sdm/mvlogistic.md
> +labels = Float64.(collect(mask(predictors[1], records)))
since this is a Bernoulli event in the model, can they not be bool?

2021-02-28 20:45 UTC, tpoisot commented on docs/src/sdm/mvlogistic.md
> +Not sure how much in detail I should explain how mvlogit works or assume a base familiarity and link to other resources.
links!

2021-02-28 20:45 UTC, tpoisot commented on docs/src/sdm/mvlogistic.md
> +Not sure how much in detail I should explain how mvlogit works or assume a base familiarity and link to other resources.
(but the rest of the paragraph is good)

2021-02-28 20:45 UTC, tpoisot commented on docs/src/sdm/mvlogistic.md
> +There is almost certaintly a more `SimpleSDMLayers`-y way to do this.
there is no obvious way at the moment...

2021-02-28 20:45 UTC, tpoisot commented on src/lib/overloads.jl
> +"""
you'll need to rebase the current version of master

2021-03-02 14:44 UTC, tpoisot commented
So this apparently times out. Is the example so large?

2021-03-02 14:45 UTC, tpoisot commented
One thing I had to do for the Mangal documentation was to have Weave documents, which we can run in parallel, for the most intensive tasks.

2021-03-02 18:18 UTC, gottacatchenall commented
Weaving might be necessary as any other examples are likely to be more complex and slower, I can implement the changes from above and try that later, would weaving to html in  `/docs/sdm/` work with the docs CI?

2021-03-02 20:06 UTC, tpoisot commented
or.... we can make a repo for vignettes? Let's take a few days to think about it.

2021-03-02 23:34 UTC, tpoisot commented
Alternatively, what do you think about getting some examples from Berteaux's book? They mostly use bioclim 1 and 12, and we can still do some work with two predictors for now.

2021-03-03 15:56 UTC, gottacatchenall commented
that works, also Fletcher&Fortin 2019 have a lot of examples and data sets with implementations in R, wouldn't be hard to port them

2021-05-14 15:13 UTC, closed without merging